repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args:
      - "--markdown-linebreak-ext=md"
-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
    -   id: mypy
        args: []  # If not specified, pre-commit will run mypy with `--ignore-missing-imports`.
        additional_dependencies:
            - types-requests
            - pytest

default_language_version:
  python: python3.10
