repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args:
      - "--markdown-linebreak-ext=md"
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5
    hooks:
    - id: ruff-format
    - id: ruff
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    -   id: mypy
        args: []  # If not specified, pre-commit will run mypy with `--ignore-missing-imports`.
        additional_dependencies:
            - types-requests
            - pytest

default_language_version:
  python: python3.10
